//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epcd_comp_app.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("epcd_comp_app.Resources.Views.Home.Form", typeof(Views_Home_Form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الرباعي.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصيغ المقبولة [jpg,jpeg,png].
        /// </summary>
        internal static string ImageRequirements {
            get {
                return ResourceManager.GetString("ImageRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع التقاط الصورة.
        /// </summary>
        internal static string PhotoLocation {
            get {
                return ResourceManager.GetString("PhotoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكان الذي تم التصوير فيه اذا لم يتوفر حاول تقدير اقرب موقع التقطت فيه الصورة, انسخ رابط موقع التقاط الصورة من قوقل ماب والصقه هنا مثال https://maps.app.goo.gl/t2AFYkifCRLbbo3eA.
        /// </summary>
        internal static string PhotoLocationRequirements {
            get {
                return ResourceManager.GetString("PhotoLocationRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدف الصورة.
        /// </summary>
        internal static string PhotoPurpose {
            get {
                return ResourceManager.GetString("PhotoPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الصورة.
        /// </summary>
        internal static string PhotoTitle {
            get {
                return ResourceManager.GetString("PhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضغط على المربع اقرار بقراءة وقبول شروط المسابقة.
        /// </summary>
        internal static string TermsAgreement {
            get {
                return ResourceManager.GetString("TermsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسابقة التصوير البيئي لعام 2024.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
